#index:
#    path: /
#    controller: App\Controller\DefaultController::index


page_howitworks:
    path: /how-it-works
    controller: App\Controller\PageController::howItWorks

page_privacy:
    path: /privacy
    controller: App\Controller\PageController::privacy

app_note_test:
    path: /note-crypto-test
    controller: App\Controller\NoteController::test

app_note_index:
    path: /
    controller: App\Controller\NoteController::createView
    methods: GET

app_note_create_save:
    path: /
    controller: App\Controller\NoteController::storeNote
    methods: POST

app_note_view:
    path: /n/{guid}
    controller: App\Controller\NoteController::viewIndex
    methods: GET

app_note_read:
    path: /n/{guid}
    controller: App\Controller\NoteController::getNote
    methods: POST

app_note_manual_delete:
    path: /delete/n/{guid}
    controller: App\Controller\NoteController::deleteNote
    methods: POST
