#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_note_test:
    path: /n/test
    controller: App\Controller\NoteController::test

app_note_create_view:
    path: /n/create
    controller: App\Controller\NoteController::createView
    methods: GET

app_note_index:
    path: /
    controller: App\Controller\NoteController::createView
    methods: GET

app_note_create_save:
    path: /n/create
    controller: App\Controller\NoteController::createSave
    methods: POST

app_note_view:
    path: /n/{guid}
    controller: App\Controller\NoteController::view
    methods: GET

app_note_read:
    path: /n/{guid}
    controller: App\Controller\NoteController::read
    methods: POST


