#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_note_test:
    path: /n/test
    controller: App\Controller\NoteController::test

app_note_create:
    path: /n/create
    controller: App\Controller\NoteController::create

app_note_view:
    path: /n/{guid}
    controller: App\Controller\NoteController::view

app_note_read:
    path: /n/{guid}
    controller: App\Controller\NoteController::read
    methods: POST


